apiVersion: v1
kind: Service
metadata:
  name: springboot-argocd-demo
spec:
  selector:
    app: springboot-argocd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
